### ISSUE TITLE
Issues with SLURM

### ISSUE THREAD

**Issue by SZubeen** [mingkai-zheng/SimMatch#10]
Sir, I'm having issues with SLURM while running the code. My device is Windows and I have no luck in using SLURM. I use Jupyter to run the codes. Is there any roundabout way? Regards.

**Comment by mingkai-zheng** [comment]
Please refer to [this repository](https://github.com/amazon-science/exponential-moving-average-normalization) as a reference to edit your code

**Comment by SZubeen** [comment]
Thank you, sir!
