### ISSUE TITLE
validation set

### ISSUE THREAD

**Issue by hzhz2020** [mingkai-zheng/SimMatch#8]
Dear Author
Thank you for the exciting work!
I have a clarification question: What validation set size did you use? I didn't find such information in the paper

**Comment by zdundjkl** [comment]
In past 3 months,I still can't understand the 'aggregate' and 'unfold' meaning.How to combine q and p.

**Comment by zdundjkl** [comment]
You have already done with yolov8？



发自我的iPhone


------------------ Original ------------------
From: Mingkai Zheng ***@***.***&gt;
Date: Thu,Dec 14,2023 9:26 PM
To: mingkai-zheng/SimMatch ***@***.***&gt;
Cc: zdundjkl ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [mingkai-zheng/SimMatch] validation set (Issue #8)





 
Closed #8 as completed.
