### ISSUE TITLE
How to reproduce the ImageNet result?

### ISSUE THREAD

**Issue by hzhz2020** [mingkai-zheng/SimMatch#9]
Where is the triain.txt file for runing the imagenet code?
https://github.com/mingkai-zheng/SimMatch/blob/c685c381d32e24ca5e6938a13bea8ebeedceb684/data/imagenet.py#L129

Wouldn't we need this file to run the ImageNet code?

**Comment by mingkai-zheng** [comment]
This train.txt file contains all the (image_name, image_path) in the imagenet dataset, you can manually generate it as long as you have the imagenet dataset on your server. As mentioned in the README.md file, you probably need to change this function to fit your own server environments.

**Comment by hzhz2020** [comment]
Thank you for your response. Can you provide a script as demo for generating this train.txt? Sorry i haven't used ImageNet data before.

**Comment by mingkai-zheng** [comment]
Do you have your imagenet data installed?

**Comment by hzhz2020** [comment]
Yes i already have the imagenet data installed. I downloaded it from the ImageNet website the ILSVRC2012 dataset. The structure of my downloaded data is like
"--n01440764
        --n01440764_10026.JPEG
        --n01440764_10027.JPEG
        .......
  --n01443537
      --n01443537_10007.JPEG
      --n01443537_10014.JPEG
      ....
....
"
So i feel like this isn't in the same format as what you described? Please let me know if i should do something else instead?

Thank you so much!


Thank you so much!

**Comment by mingkai-zheng** [comment]
The format of train.txt file would be like the follows:
```
n01440764/n01440764_10026.JPEG 0
n01440764/n01440764_10027.JPEG 0
n01440764/n01440764_10029.JPEG 0
n01440764/n01440764_10040.JPEG 0
n01440764/n01440764_10042.JPEG 0
n01440764/n01440764_10043.JPEG 0
n01440764/n01440764_10048.JPEG 0
n01440764/n01440764_10066.JPEG 0
n01440764/n01440764_10074.JPEG 0
n01440764/n01440764_1009.JPEG 0
...
```

**Comment by hzhz2020** [comment]
thank you! i will try.
